language: node_js
node_js:
  - "v4.8.3"
  - "v6.10.1"
sudo: false
cache:
  directories:
    - node_modules
env:
before_install:
before_script:
  #  - node bin/wwww > /dev/null 2>&1 &
  - node bin/wwww &
