language: node_js
# When changing node version also update it on line 35.
node_js:
  - "0.10"
  - "0.12"
sudo: false
cache:
  directories:
    - node_modules
env:
before_install:
  - git clone https://github.com/vpp/timeoff-management.git ~/tom
  - cd ~/tom
  - git checkout phantomjs_integration_tests
before_script:
  - ulimit -n 2560 ; node bin/wwww > /dev/null &
