apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
  labels: 
    app: gorilla-logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gorilla-logic
  template:
    metadata:
      labels:
        app: gorilla-logic
    spec:
      containers:
      - name: time-app
        image: gcr.io/gorilla-logic/time-app-image@sha256:f42ee366fce7d94e95507fa7441ce5b37ca82dc9f379edd86a27bd9ea777250e
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: time-app-service
spec:
  selector:
    app.kubernetes.io/name: gorilla-logic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
