apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
  labels: 
    app: gorilla-logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gorilla-logic
  template:
    metadata:
      labels:
        app: gorilla-logic
    spec:
      containers:
      - name: time-app
        image: gcr.io/gorilla-logic/time-app-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: time-app-service
spec:
  selector:
    app.kubernetes.io/name: time-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
