name: DEPLOY_Dev_tiemoff

on:
  push:
    branches: ["**"]
    paths:
      - .github/workflows/deploy-dev-timeoff.yaml

env:
  PROJECT_ID: big-liberty-373120
  DOCKER_IMAGE: timeoff

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading code
        uses: actions/checkout@v3
      
      - name: Installing node dependencies
        run: npm install

      - name: Running tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'read'
    steps:
    - name: Downloading code
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        token_format: 'access_token'

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    
    - name: Building image
      run: docker build --tag ${{ env.DOCKER_IMAGE }}:latest .

    - name: Tag image 
      run: docker tag timeoff gcr.io/${{ env.PROJECT_ID }}/${{ env.DOCKER_IMAGE }}:$GITHUB_SHA

    - name: Push image to registry
      run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.DOCKER_IMAGE }}:$GITHUB_SHA