name: Monet Deploy Test

on:
  push:
    branches:
    - develop

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Build y Publish

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          docker_login=$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
          eval "${docker_login}"

      - name: Extraer nombre branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build y push docker image [Branch]
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          ECR_DOMAIN: ${{ secrets.ECR_DOMAIN }}
        run: |
          docker build -t ${ECR_DOMAIN}/monet-webapp:PR-${PR_NUMBER} .
          docker push ${ECR_DOMAIN}/monet-webapp:PR-${PR_NUMBER}

      - name: K8S deploy
        run: |
          aws eks --region us-east-1 update-kubeconfig --name default
          ./deploy.sh
