name: Docker Image CI

on:
  push:
    branches: [ "master", "feature/gorilla-test" ]
  pull_request:
    branches: [ "master", "feature/gorilla-test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag timeoff-management-app:latest
